== Introduction

The Data Repository Service (DRS) API provides a generic interface to data repositories so data consumers, including workflow systems, can access data in a single, standard way regardless of where it's stored and how it's managed. This document describes the DRS API and provides details on the specific endpoints, request formats, and responses. It is intended for developers of DRS-compatible services and of clients that will call these DRS services.

The primary functionality of DRS is to map a logical ID to a means for physically retrieving the data represented by the ID. The sections below describe the characteristics of those IDs, the types of data supported, and how the mapping works.

== DRS API Principles

=== DRS IDs

Each implementation of DRS can choose its own id scheme, as long as it follows these guidelines:

* DRS IDs are strings made up of uppercase and lowercase letters, decimal digits, hypen, period, underscore and tilde [A-Za-z0-9.-_~]. See https://tools.ietf.org/html/rfc3986#section-2.3[RFC 3986 § 2.3].
* Note to server implementors: internal IDs can contain other characters, but they MUST be encoded into valid DRS IDs whenever exposed by the API.
* One DRS ID MUST always return the same object data (or, in the case of a collection, the same set of objects). This constraint aids with reproducibility.
* DRS v1 does NOT support semantics around multiple versions of an object. (For example, there’s no notion of “get latest version” or “list all versions”.) Individual implementation MAY choose an ID scheme that includes version hints.
* DRS implementations MAY have more than one ID that maps to the same object.

=== DRS Prefixes

Each implementation of DRS MAY use a persistent identifier to support long term access to objects. The persistent identifier MUST include a component that does not change, known as the prefix. A prefix has a scheme and an identifier. The scheme denotes the resolution service such as `ark:` for [Archival Resource Keys](https://n2t.net/e/ark_ids.html) or `dg` for [dataguids](https://dataguids.org/)
The identifier of the prefix is a unique string assigned by the resolution service. Once assigned, it CAN be shared with other resolvers so they can resolve the prefixes as well.

Example prefix {scheme}{identifier} dg.1234

It is important to understand that prefixes are immutable. Once a prefix is assigned to an organization/DRS implementation it won't change. However, the host that this prefix points to can be updated.

=== DRS URIs

For convenience, including when passing content references to a WES server, we define a URI syntax for DRS-accessible content. Strings of the form `drs://<server>/<id>` or `drs://<scheme><identifier>/<id>` mean _“you can fetch the content with DRS id `<id>` from the DRS server at `<server>` with prefix <scheme><identifier> if provided "_.

For example, if a WES server was asked to process `drs://drs.example.org/314159`, it would know that it could issue a GET request to `https://drs.example.org/ga4gh/drs/v1/objects/314159` to learn how to fetch that object.

=== DRS Datatypes

DRS v1 supports two types of content:

* a _blob_ is like a file -- it's a single blob of bytes, represented by a `DrsObject` without a `contents` array
* a _bundle_ is like a folder -- it's a collection of other DRS content (either blobs or bundles), represented by a `DrsObject` with a `contents` array

=== Read-only

DRS v1 is a read-only API. We expect that each implementation will define its own mechanisms and interfaces (graphical and/or programmatic) for adding and updating data.

=== Standards

The DRS API specification is written in OpenAPI and embodies a RESTful service philosophy.  It uses JSON in requests and responses and standard HTTPS for information transport.

== Authorization & Authentication

=== Making DRS Requests

The DRS implementation is responsible for defining and enforcing an authorization policy that determines which users are allowed to make which requests. GA4GH recommends that DRS implementations use an OAuth 2.0 https://oauth.net/2/bearer-tokens/[bearer token], although they can choose other mechanisms if appropriate.

=== Fetching DRS Objects

The DRS API allows implementers to support a variety of different content access policies, depending on what `AccessMethod` s they return:

* public content:
** server provides an `access_url` with a `url` and no `headers`
** caller fetches the object bytes without providing any auth info
* private content that requires the caller to have out-of-band auth knowledge (e.g. service account credentials):
** server provides an `access_url` with a `url` and no `headers`
** caller fetches the object bytes, passing the auth info they obtained out-of-band
* private content that requires the caller to pass an Authorization token:
** server provides an `access_url` with a `url` and `headers`
** caller fetches the object bytes, passing auth info via the specified header(s)
* private content that uses an expensive-to-generate auth mechanism (e.g. a signed URL):
** server provides an `access_id`
** caller passes the `access_id` to the `/access` endpoint
** server provides an `access_url` with the generated mechanism (e.g. a signed URL in the `url` field)
** caller fetches the object bytes from the `url` (passing auth info from the specified headers, if any)

DRS implementers should ensure their solutions restrict access to targets as much as possible, detect attempts to exploit through log monitoring, and they are prepared to take action if an exploit in their DRS implementation is detected.

=== DRS Resolution

When making DRS requests if a 404 is encountered, the DRS implementation CAN use the DRS prefix to resolve the identifiers. DRS implementors can use a resolution service like http://n2t.net/[n2t], http://identifiers.org/[identifiers.org], or https://dataguids.org/[dataguids] (for `dg.`) to resolve prefixes. This request will give a HTTP 302 response with the redirect to the new URL associated with the DRS implementation. This new URL can then be cached to be used for subsequent DRS requests.

There is no need to pass any authorization headers to the resolution service
