/*
 * Data Object Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ga4gh.dos;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import ga4gh.dos.DataBundle;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * CreateDataBundleRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-13T15:01:18.579-07:00")
public class CreateDataBundleRequest {
  @SerializedName("data_bundle")
  private DataBundle dataBundle = null;

  public CreateDataBundleRequest dataBundle(DataBundle dataBundle) {
    this.dataBundle = dataBundle;
    return this;
  }

   /**
   * Get dataBundle
   * @return dataBundle
  **/
  @ApiModelProperty(value = "")
  public DataBundle getDataBundle() {
    return dataBundle;
  }

  public void setDataBundle(DataBundle dataBundle) {
    this.dataBundle = dataBundle;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateDataBundleRequest createDataBundleRequest = (CreateDataBundleRequest) o;
    return Objects.equals(this.dataBundle, createDataBundleRequest.dataBundle);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dataBundle);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateDataBundleRequest {\n");
    
    sb.append("    dataBundle: ").append(toIndentedString(dataBundle)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

