/*
 * Data Object Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ga4gh.dos;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import ga4gh.dos.Checksum;
import ga4gh.dos.SystemMetadata;
import ga4gh.dos.UserMetadata;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;

/**
 * DataBundle
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-13T15:01:18.579-07:00")
public class DataBundle {
  @SerializedName("id")
  private String id = null;

  @SerializedName("data_object_ids")
  private List<String> dataObjectIds = null;

  @SerializedName("created")
  private OffsetDateTime created = null;

  @SerializedName("updated")
  private OffsetDateTime updated = null;

  @SerializedName("version")
  private String version = null;

  @SerializedName("checksums")
  private List<Checksum> checksums = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("aliases")
  private List<String> aliases = null;

  @SerializedName("system_metadata")
  private SystemMetadata systemMetadata = null;

  @SerializedName("user_metadata")
  private UserMetadata userMetadata = null;

  public DataBundle id(String id) {
    this.id = id;
    return this;
  }

   /**
   * REQUIRED An identifier, unique to this Data Bundle
   * @return id
  **/
  @ApiModelProperty(value = "REQUIRED An identifier, unique to this Data Bundle")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public DataBundle dataObjectIds(List<String> dataObjectIds) {
    this.dataObjectIds = dataObjectIds;
    return this;
  }

  public DataBundle addDataObjectIdsItem(String dataObjectIdsItem) {
    if (this.dataObjectIds == null) {
      this.dataObjectIds = new ArrayList<String>();
    }
    this.dataObjectIds.add(dataObjectIdsItem);
    return this;
  }

   /**
   * REQUIRED The list of Data Objects that this Data Bundle contains.
   * @return dataObjectIds
  **/
  @ApiModelProperty(value = "REQUIRED The list of Data Objects that this Data Bundle contains.")
  public List<String> getDataObjectIds() {
    return dataObjectIds;
  }

  public void setDataObjectIds(List<String> dataObjectIds) {
    this.dataObjectIds = dataObjectIds;
  }

  public DataBundle created(OffsetDateTime created) {
    this.created = created;
    return this;
  }

   /**
   * REQUIRED Timestamp of object creation in RFC3339.
   * @return created
  **/
  @ApiModelProperty(value = "REQUIRED Timestamp of object creation in RFC3339.")
  public OffsetDateTime getCreated() {
    return created;
  }

  public void setCreated(OffsetDateTime created) {
    this.created = created;
  }

  public DataBundle updated(OffsetDateTime updated) {
    this.updated = updated;
    return this;
  }

   /**
   * REQUIRED Timestamp of update in RFC3339, identical to create timestamp in systems that do not support updates.
   * @return updated
  **/
  @ApiModelProperty(value = "REQUIRED Timestamp of update in RFC3339, identical to create timestamp in systems that do not support updates.")
  public OffsetDateTime getUpdated() {
    return updated;
  }

  public void setUpdated(OffsetDateTime updated) {
    this.updated = updated;
  }

  public DataBundle version(String version) {
    this.version = version;
    return this;
  }

   /**
   * REQUIRED A string representing a version, some systems may use checksum, a RFC3339 timestamp, or incrementing version number. For systems that do not support versioning please use your update timestamp as your version.
   * @return version
  **/
  @ApiModelProperty(value = "REQUIRED A string representing a version, some systems may use checksum, a RFC3339 timestamp, or incrementing version number. For systems that do not support versioning please use your update timestamp as your version.")
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }

  public DataBundle checksums(List<Checksum> checksums) {
    this.checksums = checksums;
    return this;
  }

  public DataBundle addChecksumsItem(Checksum checksumsItem) {
    if (this.checksums == null) {
      this.checksums = new ArrayList<Checksum>();
    }
    this.checksums.add(checksumsItem);
    return this;
  }

   /**
   * REQUIRED At least one checksum must be provided. The data bundle checksum is computed over all the checksums of the Data Objects that bundle contains.
   * @return checksums
  **/
  @ApiModelProperty(value = "REQUIRED At least one checksum must be provided. The data bundle checksum is computed over all the checksums of the Data Objects that bundle contains.")
  public List<Checksum> getChecksums() {
    return checksums;
  }

  public void setChecksums(List<Checksum> checksums) {
    this.checksums = checksums;
  }

  public DataBundle description(String description) {
    this.description = description;
    return this;
  }

   /**
   * OPTIONAL A human readable description.
   * @return description
  **/
  @ApiModelProperty(value = "OPTIONAL A human readable description.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public DataBundle aliases(List<String> aliases) {
    this.aliases = aliases;
    return this;
  }

  public DataBundle addAliasesItem(String aliasesItem) {
    if (this.aliases == null) {
      this.aliases = new ArrayList<String>();
    }
    this.aliases.add(aliasesItem);
    return this;
  }

   /**
   * OPTIONAL A list of strings that can be used to identify this Data Bundle.
   * @return aliases
  **/
  @ApiModelProperty(value = "OPTIONAL A list of strings that can be used to identify this Data Bundle.")
  public List<String> getAliases() {
    return aliases;
  }

  public void setAliases(List<String> aliases) {
    this.aliases = aliases;
  }

  public DataBundle systemMetadata(SystemMetadata systemMetadata) {
    this.systemMetadata = systemMetadata;
    return this;
  }

   /**
   * Get systemMetadata
   * @return systemMetadata
  **/
  @ApiModelProperty(value = "")
  public SystemMetadata getSystemMetadata() {
    return systemMetadata;
  }

  public void setSystemMetadata(SystemMetadata systemMetadata) {
    this.systemMetadata = systemMetadata;
  }

  public DataBundle userMetadata(UserMetadata userMetadata) {
    this.userMetadata = userMetadata;
    return this;
  }

   /**
   * Get userMetadata
   * @return userMetadata
  **/
  @ApiModelProperty(value = "")
  public UserMetadata getUserMetadata() {
    return userMetadata;
  }

  public void setUserMetadata(UserMetadata userMetadata) {
    this.userMetadata = userMetadata;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DataBundle dataBundle = (DataBundle) o;
    return Objects.equals(this.id, dataBundle.id) &&
        Objects.equals(this.dataObjectIds, dataBundle.dataObjectIds) &&
        Objects.equals(this.created, dataBundle.created) &&
        Objects.equals(this.updated, dataBundle.updated) &&
        Objects.equals(this.version, dataBundle.version) &&
        Objects.equals(this.checksums, dataBundle.checksums) &&
        Objects.equals(this.description, dataBundle.description) &&
        Objects.equals(this.aliases, dataBundle.aliases) &&
        Objects.equals(this.systemMetadata, dataBundle.systemMetadata) &&
        Objects.equals(this.userMetadata, dataBundle.userMetadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, dataObjectIds, created, updated, version, checksums, description, aliases, systemMetadata, userMetadata);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DataBundle {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    dataObjectIds: ").append(toIndentedString(dataObjectIds)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    updated: ").append(toIndentedString(updated)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    checksums: ").append(toIndentedString(checksums)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    aliases: ").append(toIndentedString(aliases)).append("\n");
    sb.append("    systemMetadata: ").append(toIndentedString(systemMetadata)).append("\n");
    sb.append("    userMetadata: ").append(toIndentedString(userMetadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

