/*
 * Data Object Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ga4gh.dos;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import ga4gh.dos.DataBundle;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * GetDataBundleVersionsResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-13T15:01:18.579-07:00")
public class GetDataBundleVersionsResponse {
  @SerializedName("data_bundles")
  private List<DataBundle> dataBundles = null;

  public GetDataBundleVersionsResponse dataBundles(List<DataBundle> dataBundles) {
    this.dataBundles = dataBundles;
    return this;
  }

  public GetDataBundleVersionsResponse addDataBundlesItem(DataBundle dataBundlesItem) {
    if (this.dataBundles == null) {
      this.dataBundles = new ArrayList<DataBundle>();
    }
    this.dataBundles.add(dataBundlesItem);
    return this;
  }

   /**
   * REQUIRED All versions of the Data Bundles that match the GetDataBundleVersions request.
   * @return dataBundles
  **/
  @ApiModelProperty(value = "REQUIRED All versions of the Data Bundles that match the GetDataBundleVersions request.")
  public List<DataBundle> getDataBundles() {
    return dataBundles;
  }

  public void setDataBundles(List<DataBundle> dataBundles) {
    this.dataBundles = dataBundles;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetDataBundleVersionsResponse getDataBundleVersionsResponse = (GetDataBundleVersionsResponse) o;
    return Objects.equals(this.dataBundles, getDataBundleVersionsResponse.dataBundles);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dataBundles);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetDataBundleVersionsResponse {\n");
    
    sb.append("    dataBundles: ").append(toIndentedString(dataBundles)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

