/*
 * Data Object Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ga4gh.dos;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import ga4gh.dos.DataObject;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * GetDataObjectVersionsResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-13T15:01:18.579-07:00")
public class GetDataObjectVersionsResponse {
  @SerializedName("data_objects")
  private List<DataObject> dataObjects = null;

  public GetDataObjectVersionsResponse dataObjects(List<DataObject> dataObjects) {
    this.dataObjects = dataObjects;
    return this;
  }

  public GetDataObjectVersionsResponse addDataObjectsItem(DataObject dataObjectsItem) {
    if (this.dataObjects == null) {
      this.dataObjects = new ArrayList<DataObject>();
    }
    this.dataObjects.add(dataObjectsItem);
    return this;
  }

   /**
   * REQUIRED All versions of the Data Objects that match the GetDataObjectVersions request.
   * @return dataObjects
  **/
  @ApiModelProperty(value = "REQUIRED All versions of the Data Objects that match the GetDataObjectVersions request.")
  public List<DataObject> getDataObjects() {
    return dataObjects;
  }

  public void setDataObjects(List<DataObject> dataObjects) {
    this.dataObjects = dataObjects;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetDataObjectVersionsResponse getDataObjectVersionsResponse = (GetDataObjectVersionsResponse) o;
    return Objects.equals(this.dataObjects, getDataObjectVersionsResponse.dataObjects);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dataObjects);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetDataObjectVersionsResponse {\n");
    
    sb.append("    dataObjects: ").append(toIndentedString(dataObjects)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

