/*
 * Data Object Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ga4gh.dos;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import ga4gh.dos.DataObject;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * A list of Data Objects matching the requested parameters, and a paging token, that can be used to retrieve more results.
 */
@ApiModel(description = "A list of Data Objects matching the requested parameters, and a paging token, that can be used to retrieve more results.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-13T15:01:18.579-07:00")
public class ListDataObjectsResponse {
  @SerializedName("data_objects")
  private List<DataObject> dataObjects = null;

  @SerializedName("next_page_token")
  private String nextPageToken = null;

  public ListDataObjectsResponse dataObjects(List<DataObject> dataObjects) {
    this.dataObjects = dataObjects;
    return this;
  }

  public ListDataObjectsResponse addDataObjectsItem(DataObject dataObjectsItem) {
    if (this.dataObjects == null) {
      this.dataObjects = new ArrayList<DataObject>();
    }
    this.dataObjects.add(dataObjectsItem);
    return this;
  }

   /**
   * The list of Data Objects.
   * @return dataObjects
  **/
  @ApiModelProperty(value = "The list of Data Objects.")
  public List<DataObject> getDataObjects() {
    return dataObjects;
  }

  public void setDataObjects(List<DataObject> dataObjects) {
    this.dataObjects = dataObjects;
  }

  public ListDataObjectsResponse nextPageToken(String nextPageToken) {
    this.nextPageToken = nextPageToken;
    return this;
  }

   /**
   * The continuation token, which is used to page through large result sets. Provide this value in a subsequent request to return the next page of results. This field will be empty if there aren&#39;t any additional results.
   * @return nextPageToken
  **/
  @ApiModelProperty(value = "The continuation token, which is used to page through large result sets. Provide this value in a subsequent request to return the next page of results. This field will be empty if there aren't any additional results.")
  public String getNextPageToken() {
    return nextPageToken;
  }

  public void setNextPageToken(String nextPageToken) {
    this.nextPageToken = nextPageToken;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListDataObjectsResponse listDataObjectsResponse = (ListDataObjectsResponse) o;
    return Objects.equals(this.dataObjects, listDataObjectsResponse.dataObjects) &&
        Objects.equals(this.nextPageToken, listDataObjectsResponse.nextPageToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dataObjects, nextPageToken);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListDataObjectsResponse {\n");
    
    sb.append("    dataObjects: ").append(toIndentedString(dataObjects)).append("\n");
    sb.append("    nextPageToken: ").append(toIndentedString(nextPageToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

