/*
 * Data Object Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ga4gh.dos;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import ga4gh.dos.SystemMetadata;
import ga4gh.dos.UserMetadata;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * URL
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-13T15:01:18.579-07:00")
public class URL {
  @SerializedName("url")
  private String url = null;

  @SerializedName("system_metadata")
  private SystemMetadata systemMetadata = null;

  @SerializedName("user_metadata")
  private UserMetadata userMetadata = null;

  public URL url(String url) {
    this.url = url;
    return this;
  }

   /**
   * REQUIRED A URL that can be used to access the file.
   * @return url
  **/
  @ApiModelProperty(value = "REQUIRED A URL that can be used to access the file.")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public URL systemMetadata(SystemMetadata systemMetadata) {
    this.systemMetadata = systemMetadata;
    return this;
  }

   /**
   * Get systemMetadata
   * @return systemMetadata
  **/
  @ApiModelProperty(value = "")
  public SystemMetadata getSystemMetadata() {
    return systemMetadata;
  }

  public void setSystemMetadata(SystemMetadata systemMetadata) {
    this.systemMetadata = systemMetadata;
  }

  public URL userMetadata(UserMetadata userMetadata) {
    this.userMetadata = userMetadata;
    return this;
  }

   /**
   * Get userMetadata
   * @return userMetadata
  **/
  @ApiModelProperty(value = "")
  public UserMetadata getUserMetadata() {
    return userMetadata;
  }

  public void setUserMetadata(UserMetadata userMetadata) {
    this.userMetadata = userMetadata;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    URL URL = (URL) o;
    return Objects.equals(this.url, URL.url) &&
        Objects.equals(this.systemMetadata, URL.systemMetadata) &&
        Objects.equals(this.userMetadata, URL.userMetadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(url, systemMetadata, userMetadata);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class URL {\n");
    
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    systemMetadata: ").append(toIndentedString(systemMetadata)).append("\n");
    sb.append("    userMetadata: ").append(toIndentedString(userMetadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

